\import Paths.Meta
\import Tests.Definitions
\import hw02
\import lect02

{- | Tests for problem 1 -}
\func test-1-1 : tail test-list-1 = test-list-1-tail => idp
\func test-1-2 : tail test-list-2 = test-list-2-tail => idp
\func test-1-3 : tail test-list-3 = test-list-3-tail => idp
\func test-1-4 : tail test-list-4 = test-list-4-tail => idp
\func test-1-5 : tail test-list-5 = test-list-5-tail => idp
\func test-1-6 : tail test-list-6 = test-list-6-tail => idp
\func test-1-7 : tail test-list-7 = test-list-7-tail => idp
\func test-1-8 : tail test-list-8 = test-list-8-tail => idp
\func test-1-9 : tail test-list-9 = test-list-9-tail => idp

{- | Tests for problem 2 -}

\func test-2-1 : sort test-NatOrder1 test-list-1 = test-list-1-sort-1 => {?}

