\import lect01
\import hw01


{- | Tests for problem 2 -}

\func test-2-second-1 : second 3 4 5 = 4 => idp
\func test-2-second-2 : second 10 0 0 = 0 => idp
\func test-2-second-3 : second 1000 1000 1000 = 10000 => idp
\func test-2-second-4 : second 10 (5 + 4) 4 = 9 => idp

\func test-2-compose-1 : compose (5 + ) (4 + ) 3 = 12 => idp
\func test-2-compose-2 : compose (5 * ) (4 + ) 3 = 35 => idp
\func test-2-compose-3 : compose (0 * ) (100000 +  ) 198 = 0 => idp
\func test-2-compose-4 : compose (1 * ) (100000 +  ) 15 = 100015 => idp

\func test-2-flip-1 : flip (+) 2 3 = flip (+) 3 2 => idp
\func test-2-flip-2 : flip (+) 0 1000 = flip (+) 1000 0 => idp

-- следующие два тесты должны проходить только если уже написана функция mod
\func test-2-flip-3 : flip mod 10 20 = 10 => idp
\func test-2-flip-4 : flip mod 15 4 = 4 => idp


{- | Tests for problem 5 -}
\func test-5-1 : (true || true) = true => idp
\func test-5-2 : (true || false) = false => idp
\func test-5-3 : false || true = false => idp
\func test-5-4 : false || false = false => idp

{- | Tests for problem 6 -}

\func test-6-pow-1 : 5 ^ 3 = 125 => idp
\func test-6-pow-2 : 1 ^ 0 = 1 => idp
\func test-6-pow-3 : 0 ^ 0 = 1 => idp
\func test-6-pow-4 : 1000 ^ 1 = 1000 => idp

\func test-6-fac-1 : fac 0 = 1 => idp
\func test-6-fac-2 : fac 10 = 3628800 => idp
\func test-6-fac-3 : fac 8 = 40320 => idp
\func test-6-fac-4 : fac 4 = 24 => idp
\func test-6-fac-5 : fac 5 = 120 => idp

{- | Tests for problem 7 -}

\func test-7-mod-1 : mod 5 10 = 5 => idp
\func test-7-mod-2 : mod 10 5 = 0 => idp
\func test-7-mod-3 : mod 9 7 = 2 => idp
\func test-7-mod-4 : mod 13 12 = 1 => idp
\func test-7-mod-5 : mod 1879 1 = 0 => idp
\func test-7-mod-6 : mod 0 198 = 0 => idp
\func test-7-mod-7 : mod 190 0 = 0 => idp

\func test-7-gcd-1 : gcd 10 5 = 5 => idp
\func test-7-gcd-2 : gcd 7 13 = 1 => idp
\func test-7-gcd-3 : gcd 6 15 = 3 => idp
\func test-7-gcd-4 : gcd 9 6 = 3 => idp
\func test-7-gcd-5 : gcd 10 1 = 1 => idp
\func test-7-gcd-6 : gcd 12 18 = 6 => idp
\func test-7-gcd-7 : gcd 10 0 = 0 => idp
\func test-7-gcd-11 : gcd 5 10 = 5 => idp
\func test-7-gcd-12 : gcd 13 7 = 1 => idp
\func test-7-gcd-13 : gcd 15 6 = 3 => idp
\func test-7-gcd-14 : gcd 6 9 = 3 => idp
\func test-7-gcd-15 : gcd 1 10 = 1 => idp
\func test-7-gcd-16 : gcd 18 12 = 6 => idp
\func test-7-gcd-17 : gcd 0 10 = 0 => idp

